version: '2'
services:
    testejhip-app:
        image: testejhip
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testejhip-mysql:3306/testejhip?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testejhip-mysql:
        extends:
            file: mysql.yml
            service: testejhip-mysql
